# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    build: ./docker-database
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

  ww3:
    build: .
    ports:
      - 3000:3000

  nginx:
    build: ./nginx
    ports:
      - 80:80
